### ISSUE TITLE
ITV Regional 

### ISSUE THREAD

**Issue by Pter0845178** [Jasmeet181/mediaportal-uk-logos#36] opened 2022-11-20 14:21 UTC
Possible to add ITV Regional channels Logos 

https://en.wikipedia.org/wiki/List_of_ITV_regions
https://www.itvmedia.co.uk/advertising-on-itv/regional-advertising

**Comment by Jasmeet181** [comment] 2022-11-20 19:13
Duplicate of #26

**Closed by Jasmeet181** 2022-11-20 19:13 UTC
